branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
global:
  application_name: file-server
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: eu-central-1
  profile: eb-cli
  repository: null
  sc: null
